#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyserial"]
# ///
"""Run the paired-board WS63 SLE S3 SSAP data reset matrix."""

from __future__ import annotations

import importlib.util
from pathlib import Path


BASE = Path(__file__).with_name("ws63-sle-connect-reset-matrix.py")
SPEC = importlib.util.spec_from_file_location("ws63_sle_ssap_base", BASE)
assert SPEC is not None and SPEC.loader is not None
MODULE = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(MODULE)

MODULE.SERVER_MARKERS = (
    b"RFDBG_SLE_S1_INIT_OK",
    b"RFDBG_SLE_S3_SERVER_SERVICE_OK",
    b"RFDBG_SLE_S3_SERVER_READY",
    b"RFDBG_SLE_S3_SERVER_CONNECTED",
    b"RFDBG_SLE_S3_SERVER_NOTIFY_OK",
    b"RFDBG_SLE_S3_SERVER_DISCONNECTED",
)
MODULE.CLIENT_MARKERS = (
    b"RFDBG_SLE_S1_INIT_OK",
    b"RFDBG_SLE_S3_CLIENT_CONNECTED",
    b"RFDBG_SLE_S3_CLIENT_LINK_READY",
    b"RFDBG_SLE_S3_CLIENT_EXCHANGE_OK",
    b"RFDBG_SLE_S3_CLIENT_SERVICE_OK",
    b"RFDBG_SLE_S3_CLIENT_READ_OK",
    b"RFDBG_SLE_S3_CLIENT_DATA_OK",
    b"RFDBG_SLE_S3_DATA_DISCONNECT_OK",
)
MODULE.FAILURE_MARKERS = (
    b"RFDBG_MISSING_ROM_CALLBACK",
    b"RFDBG_SLE_S1_INIT_ERR",
    b"RFDBG_SLE_S3_SERVER_ADDR_ERR",
    b"RFDBG_SLE_S3_SERVER_SERVICE_ERR",
    b"RFDBG_SLE_S3_SERVER_ANNOUNCE_ERR",
    b"RFDBG_SLE_S3_SERVER_NOTIFY_ERR",
    b"RFDBG_SLE_S3_SERVER_AUTH_ERR",
    b"RFDBG_SLE_S3_SERVER_PAIR_ERR",
    b"RFDBG_SLE_S3_SERVER_UNEXPECTED_DISCONNECT",
    b"RFDBG_SLE_S3_SERVER_EVENT_DROP",
    b"RFDBG_SLE_S3_CLIENT_START_ERR",
    b"RFDBG_SLE_S3_CLIENT_STOP_SEEK_ERR",
    b"RFDBG_SLE_S3_CLIENT_CONNECT_ERR",
    b"RFDBG_SLE_S3_CLIENT_PAIR_ERR",
    b"RFDBG_SLE_S3_CLIENT_AUTH_ERR",
    b"RFDBG_SLE_S3_CLIENT_PAIR_CFM_ERR",
    b"RFDBG_SLE_S3_CLIENT_PAIR_STATE_ERR",
    b"RFDBG_SLE_S3_CLIENT_UNEXPECTED_DISCONNECT",
    b"RFDBG_SLE_S3_CLIENT_EXCHANGE_ERR",
    b"RFDBG_SLE_S3_CLIENT_DISCOVERY_ERR",
    b"RFDBG_SLE_S3_CLIENT_SERVICE_MISSING",
    b"RFDBG_SLE_S3_CLIENT_WRITE_ERR",
    b"RFDBG_SLE_S3_CLIENT_READ_ERR",
    b"RFDBG_SLE_S3_CLIENT_DATA_ERR",
    b"RFDBG_SLE_S3_CLIENT_DISCONNECT_ERR",
    b"RFDBG_SLE_S3_CLIENT_EVENT_DROP",
)

SERVER_MARKERS = MODULE.SERVER_MARKERS
CLIENT_MARKERS = MODULE.CLIENT_MARKERS
FAILURE_MARKERS = MODULE.FAILURE_MARKERS
classify = MODULE.classify


if __name__ == "__main__":
    raise SystemExit(MODULE.main())
